name: CI

on:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t docker_exercicio .

      - name: Docker run
        run: docker run -d -p 3000:3000 --name docker_exercicio docker_exercicio

      - name: Aguardar a aplicação iniciar
        run: sleep 5

      - name: Aguardar aplicação iniciar

    run:
        for i in {1..10}; do
          curl -f http://localhost:3000 && exit 0
          sleep 2
        done
        exit 1